build:
    image: golang
    commands:
        - apt-get update
        - apt-get -y install fabric
        - go get
        - go build
deploy:
    bash:
        image: projectweekend/drone-bash
        commands:
            - fab --user=$$SUDO_USER --password=$$SUDO_PASSWORD --hosts=$$FAB_HOST deploy
