build:
    image: golang
    commands:
        - go get
        - go build
deploy:
    fabric:
        image: projectweekend/drone-fabric
        commands: fab --user=$$SUDO_USER --password=$$SUDO_PASSWORD --hosts=$$FAB_HOST deploy
