build:
    image: golang
    commands:
        - go get
        - go build
deploy:
    script:
        - echo hello
    # fabric:
    #     image: projectweekend/drone-fabric
    #     commands:
    #         - --user=$$SUDO_USER --password=$$SUDO_PASSWORD --hosts=$$FAB_HOST deploy
