rabbit:
    image: rabbitmq
    ports:
        - "5672:5672"
app:
    build: .
    command: go run main.go
    volumes:
        - ./app:/go/src/app
    ports:
        - "9000:9000"
    links:
        - rabbit
    environment:
        - API_KEY=secretapikey
